server:
  port: 37000
  address: prod-host

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prod_db-server:3306/prod_db_schema?characterEncoding=utf8&serverTimezone=UTC
    username: prod_db_user
    password: prod_db_password

cmdb:
  datasource:
    schema: prod_db_user

  security:
    enabled: true

    #Authentication provider options: NONE, LOCAL-DB or CAS. Effective ONLY when security-enabled set as true.
    authentication-provider: CAS

    #Effective ONLY when security-enabled set as true and authentication-provider turns to CAS
    cas-server-url: http://prod-cas-server-ip:8080/cas
    cas-redirect-app-addr: prod-host:8080

    #Effective ONLY when security-enabled set as true
    whitelist-ip-address:
