server:
  port: 9080
  address: localhost
  servlet:
    context-path: /wecmdb

spring:
  banner:
    location: classpath:/cmdb.txt
  profiles:
    #en-local„ÄÅch-local
    active: dev
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-server:3306/db_schema?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: db_user
    password: db_password
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none

cmdb:
  datasource:
    schema: db_user

  security:
    enabled: false

    #Authentication provider options: LOCAL, CAS or PLATFORM-AUTH. Effective ONLY when security-enabled set as true.
    authentication-provider: LOCAL

    #Effective ONLY when security-enabled set as true and authentication-provider turns to CAS
    cas-server-url: http://cas-server-ip:8080/cas
    cas-redirect-app-addr: localhost:8080

    #Effective ONLY when security-enabled set as true
    whitelist-ip-address: 127.0.0.1
logging:
  level:
    root: INFO
    com:
      webank:
        cmdb: INFO
