server:
  port: 9080
  address: localhost

spring:
  datasource:
    platform: H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cmdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=true;MV_STORE=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS wecmdb_dev\;SET SCHEMA wecmdb_dev
    username: sa
    password:
    schema: classpath:/database/ch/05.cmdb.create_table_ch.sql
    data: classpath:/database/ch/06.cmdb.insert_data_ch.sql
    sql-script-encoding: utf-8

    

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none

cmdb:
  datasource:
    schema: wecmdb_dev
  security:
    enabled: false
    whitelist-ip-address: 127.0.0.1