spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cmdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=true;MV_STORE=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS cmdb_test\;SET SCHEMA cmdb_test
    username: sa
    password:
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none

cmdb:
  datasource:
    schema: cmdb_test

logging:
  level:
    root: INFO
    com:
      webank:
        cmdb: INFO
    org:
      hibernate:
        SQL: INFO

cas-server:
  url: http://10.107.118.27:8080/cas
  enabled: false
  whitelist-ip-address: 10.107.117.154

