server:
  port: 9080
  address: localhost

spring:
  datasource:
    platform: H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cmdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=true;MV_STORE=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS wecmdb_dev\;SET SCHEMA wecmdb_dev
    username: sa
    password:
    schema: classpath:/database/en/01.cmdb.schema_en.sql
    data:
      - classpath:/database/en/02.cmdb.system.data_en.sql
      - classpath:/local/en/03.cmdb.system.data.h2_en.sql
      - classpath:/database/en/04.cmdb.experience.data_en.sql
    sql-script-encoding: utf-8
    h2: 
      console: 
        enabled: true
        path: /h2-console

    

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none

cmdb:
  datasource:
    schema: wecmdb_dev
  security:
    enabled: false
    whitelist-ip-address: localhost