server:
  port: 9080
  address: localhost
  servlet:
    context-path: /cmdb

spring:
  banner:
    location: classpath:/cmdb.txt
  profiles:
    active: dev
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tdsql-66a3mko1.sql.tencentcdb.com:75/smoke2_cmdb?characterEncoding=utf8&serverTimezone=UTC
    username: username
    password: password
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none

cmdb:
  datasource:
    schema: smoke2_cmdb
    
  #Authentication provider options: local or CAS
  authentication-provider: local

logging:
  level:
    root: INFO
    com:
      webank:
        cmdb: DEBUG

cas-server:
  url: http://localhost:8080/cas
  enabled: false
  whitelist-ip-address: 127.0.0.1  redirect-app-addr:
